### ISSUE TITLE
[Bug] Weird crash with Abnormal's "Blueprint"

### ISSUE THREAD

**Issue by MythrilBagels** [ghen-git/Thirst-Mod#1]
I threw this mod into my instance because I wanted to try it out, but the game just doesn't open. I managed to figure out that it's Thirst combined with Blueprint that stops the game from opening. There was no crash report or anything of note in the latest.log except maybe this line:
`[pool-3-thread-1/WARN] [mixin/]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zep000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.`

**Comment by MythrilBagels** [comment]
Okay, seems like that might not be the issue, as its crashing a lot regardless

**Comment by ghen-git** [comment]
Shit when does it crash?

**Comment by ghen-git** [comment]
> Okay, seems like that might not be the issue, as its crashing a lot regardless

Shit when does it crash?

**Comment by Nyancatpig** [comment]
I too have this issue, and I've found that it crashes when better combat, diagonal fences, drippy loading screen, or physics are installed, although I haven't had any problems with blueprint

The first time it crashes it closes the minecraft launcher before you can read the crash log, and if you try to open the game again it will just close the launcher with no visual of the game trying to load

**Comment by ghen-git** [comment]
Ook, the problem seems to be with the physics mod. I'm trying my best to fix it, but the fact that the mod is close-sourced isn't helping

**Comment by MythrilBagels** [comment]
It can't be just because of the Physics mod, since I don't use it
also hi Bails

**Comment by MythrilBagels** [comment]
I'll have to test it more thoroughly when I have the time

**Comment by ghen-git** [comment]
> It can't be just because of the Physics mod, since I don't use it

Idk the problem with the physics mod is extremely odd, the game literally gives a bunch of errors on the mixins and then just stops (there are no more lines on the log). The other odd thing is when my mod isn't installed, those errors are still thrown, but then the game starts up normally.

The errors themselves i believe are just because sodium isn't present, thus irrelevant to the functioning of the game.

**Comment by ghen-git** [comment]
> I'll have to test it more thoroughly when I have the time

Thank you so much for the help tho

**Comment by Nyancatpig** [comment]
Its strange how it crashes with mods like physics and dripply loading screen, I wouldn’t have thought they would interfere with eachother much

Also I thought I’d mention that the new bowls can’t be found in the creative menu or JEI, and the smelting times for water bowls seem a bit off

**Comment by ghen-git** [comment]
Only thing i can think of is im a loser noob at writing build.gradle files and might have messed up something there with the mixin versions 
And for the menu and JEI, they will be updated in version 1.1.0, which im working on rn, the only problem is i have absolutely no clue what the fuck is up with those crashes. 
Thanks so much for all the support tho

**Comment by Nyancatpig** [comment]
despite the bugs, i think this is a cool mod
i can see it becoming a staple in my playthroughs

**Comment by ghen-git** [comment]
I'm very glad to hear that, and i've also added support for other mods to add thirst to items via code like you suggested, it will be in the next update, which should come out tomorrow

**Comment by Nyancatpig** [comment]
nice
I’ll be sure to add thirst compat to my mods

**Comment by ghen-git** [comment]
This bug should be fixed with the current version of the mod, could someone give me a confirmation before i close the issue? Maybe its still present and i just haven't done enough testing
