### ISSUE TITLE
Crash on boot with 2.10 version of moonlight lib or supplementaries 2.8.0

### ISSUE THREAD

**Issue by ghost** [ghen-git/Thirst-Mod#105]
https://gist.github.com/Tomat777/2ba61b06663aa1a77e40b5f0d4ec2d69

**Comment by DaddySpin** [comment]
same error

**Comment by Vivid141** [comment]
Same issue for me. Here's my crash log.
**Crash Log:** https://mclo.gs/SXXaUyY

**Comment by ceifadorcinixtru** [comment]
same here too

**Comment by mlus-asuka** [comment]
@DaddySpin @Vivid141 @ceifadorcinixtru @Tomat777 https://modrinth.com/mod/thirst-was-taken/version/1.20.1-1.3.6
use 1.3.6a in additional file

**Comment by DaddySpin** [comment]
Out of curiosity why is it an additional file instead of a full fix?

**Comment by mlus-asuka** [comment]
> Out of curiosity why is it an additional file instead of a full fix?

I think it shouldn't be 1.3.7,because there is nothing else changed. (it has a new config value besides.)

**Comment by DaddySpin** [comment]
What broke with moonlight anyway?

**Comment by mlus-asuka** [comment]
> What broke with moonlight anyway?

it changed original codes, so i need to make new compt. you can see the detail in my commit.

**Comment by DaddySpin** [comment]
Ah I see now.

**Comment by ghost** [comment]
2.10 version of moonlight lib and supplementaries 2.8.0 works
however  2.10.10 version of moonlight lib and supplementaries 2.8.4 doesnt work 
error: https://gist.github.com/Tomat777/3c0e6320b46bf5961b914981be85ad5a

**Comment by mlus-asuka** [comment]
> 2.10 version of moonlight lib and supplementaries 2.8.0 works however 2.10.10 version of moonlight lib and supplementaries 2.8.4 doesnt work error: https://gist.github.com/Tomat777/3c0e6320b46bf5961b914981be85ad5a

okay, now we have 1.3.6b

**Comment by ghost** [comment]
yep, all good, thanks
