### ISSUE TITLE
Start crash

### ISSUE THREAD

**Issue by Qee1y** [ghen-git/Thirst-Mod#106]
version
mc 1.20.1
forge 47.2.20
mod 1.20.1-1.3.6

[crash-2024-02-23_17.03.00-client.txt](https://github.com/ghen-git/Thirst-Mod/files/14383464/crash-2024-02-23_17.03.00-client.txt)

**Comment by mlus-asuka** [comment]
BCLIB的报错你发这干啥

**Comment by Qee1y** [comment]
> BCLIB的报错你发这干啥
好吧，不太懂。主要是移除bclib或者口渴，要么对supplementaries和moon库 版本降级就不会再次崩溃

**Comment by Qee1y** [comment]
好吧，不太懂。主要是移除口渴或者bc库，以及降低锦致装饰和他的前置库版本，都不会导致崩溃。不过很抱歉，哈哈。
