### ISSUE TITLE
The thirst removal command does not work 

### ISSUE THREAD

**Issue by MayD2099** [ghen-git/Thirst-Mod#118]
![изображение_2024-04-20_124549580](https://github.com/ghen-git/Thirst-Mod/assets/106540791/4e078907-320d-4894-b137-b4d92f1e30b0)

**Comment by MayD2099** [comment]
Forge 1.20.1-1.3.7.

**Comment by mlus-asuka** [comment]
updated. you can get the fixed one on cf or modrinth
