### ISSUE TITLE
Thirst is disabled for everyone by default + Steam & Rails 

### ISSUE THREAD

**Issue by M0l1bden** [ghen-git/Thirst-Mod#119]
We suffered from bugs with food from the Brewery and trains from Steam & Rails. Today we put on a new version of Thirst was Taken, but the thirst bar just disappeared. We were afraid that the mod had stopped working, but thirst was displayed on the drinks and other items. It turns out that all players have thirst disabled by default, and because of this, they cannot run. Thirst can only be turned on by a specific player (@a does not work). There is still a bug with trains, the trolley is fixed, but the regular train is not.

**Comment by mlus-asuka** [comment]
![image](https://github.com/ghen-git/Thirst-Mod/assets/80941936/73ce2e8e-6f9e-4434-8a83-529b202fc2af)
getBytes method in CompoundTag class will return 0 if the tag didn't exists. that's the reason
