### ISSUE TITLE
Compatibility problem with Capable Cauldrons

### ISSUE THREAD

**Issue by vvvorb** [ghen-git/Thirst-Mod#12]
[crash-2023-03-15_08.13.18-fml.txt](https://github.com/ghen-git/Thirst-Mod/files/10979004/crash-2023-03-15_08.13.18-fml.txt)
![Captura de tela 2023-03-15 082303](https://user-images.githubusercontent.com/127758618/225294834-25f4f1a8-de96-4661-922c-4c59d520ea8a.png)

**Comment by ghen-git** [comment]
Thanks, i'll look into that!
