### ISSUE TITLE
[Suggestion] Please add an option in the config to make fire resistance not affect thirst

### ISSUE THREAD

**Issue by krowa3** [ghen-git/Thirst-Mod#134]
Some mods (like Traveler's backpack) add ways to have a permanent fire resistance effect making thirst obsolete.

**Comment by mlus-asuka** [comment]
![image](https://github.com/user-attachments/assets/a0374774-2083-4831-80a1-7f88c075431b)
set this to 100

**Comment by krowa3** [comment]
Oh, thank you so much. The /config command pointed me to keyword.toml so I didn't even see this file.
