### ISSUE TITLE
Mod crashes during loading on dedicated server - 1.19.2

### ISSUE THREAD

**Issue by benvalkin** [ghen-git/Thirst-Mod#14]
Congrats on updating to 1.19.2 :)

I just happened to notice that this mod was updated for 1.19.2 as it was released today, but after trying to add it to my server, I noticed that it was crashing during loading due to the following runtime exception:
`java.lang.RuntimeException: Attempted to load class dev/ghen/thirst/foundation/gui/appleskin/TooltipOverlayHandler for invalid dist DEDICATED_SERVER`

[latest.log](https://github.com/ghen-git/Thirst-Mod/files/11215952/latest.log) contains the full stacktrace. I didn't have Appleskin installed when starting my server. Would be nice if this could be fixed so that it works on servers :(

**Comment by ghen-git** [comment]
Yea thats super easy to fix, thanks for letting me know, a new patch should be up in 15 mins
