### ISSUE TITLE
Changes to API Since 1.3.7: How Do I Add Drinks?

### ISSUE THREAD

**Issue by MikulDev** [ghen-git/Thirst-Mod#146]
Hello, I'm looking to update my support for your mod to newer versions. However, the `ThirstHelper.addDrink()` and `WaterPurity.addContainer()` methods now seem to be deprecated, despite them still being referenced in the API guide on the wiki. How do I register drinks in 1.3.8 and onward?

**Comment by mlus-asuka** [comment]
subscribe `RegisterThirstValueEvent`
 https://github.com/mlus-asuka/Thirst-Mod/blob/51a85a6c5aa0909fabb83bb7a8bc9903e6c903df/src/main/java/dev/ghen/thirst/foundation/common/event/RegisterThirstValueEvent.java#L30

**Comment by MikulDev** [comment]
Awesome, thanks!
