### ISSUE TITLE
Using a water bottle to interact with Create crashes

### ISSUE THREAD

**Issue by Dr-WeiAL** [ghen-git/Thirst-Mod#15]
[crash-2023-04-15_19.44.04-client.txt](https://github.com/ghen-git/Thirst-Mod/files/11239290/crash-2023-04-15_19.44.04-client.txt)
I had a crash when using a right click Fluid Tank with a water bottle with water quality, and I have a feeling there will be other problems based on this bug

**Comment by TqLxQuanZ** [comment]
I am having this issue as well, it's not just fluid tank, it's also mechanical belt, basin and item drain too.

**Comment by ghen-git** [comment]
fixed
