### ISSUE TITLE
[Question] directly modifying a player’s thirst/hydration via API

### ISSUE THREAD

**Issue by steve-the-player** [ghen-git/Thirst-Mod#164]
I was looking into a relatively small magic mod where it directly uses a player’s hydration to power abilities instead of mana. Currently it’s just an internally handled value. 

Is there a way to directly modify a player’s hydration and thirst levels with the current API? I’m only seeing wiki entries for adding thirst values to consumable items, but not a way to directly set hydration levels or thirst rate.  
If there isn’t an API method to call for this, it would be a great thing to add. It would also help with custom potion effects and other mods

**Comment by mlus-asuka** [comment]
get Thirst Capability then you can modify it

**Comment by steve-the-player** [comment]
> get Thirst Capability then you can modify it

is that a mod? Do you have a link? Is it built in to the current Thirst mod?

**Comment by mlus-asuka** [comment]
event.getEntity().getCapability(ModCapabilities.PLAYER_THIRST)
