### ISSUE TITLE
Sand Filter not appearing / Compat request

### ISSUE THREAD

**Issue by mask3dowo** [ghen-git/Thirst-Mod#18]
The sand filter doesn't show up anywhere. I'm using the most recent versions of both your mod and Create on 1.19.2. Can't find the sand filter in creative inventory, JEI, or even the Create Ponder Menu. Was it removed?

Also, could you try to add compat for Respiteful and Collector's Reap? Thanks in advance.

**Comment by ghen-git** [comment]
You can find the sand filter in the create inventory tab, around these items

![image](https://user-images.githubusercontent.com/71780401/234058074-e554f9a5-e3c8-4db1-b9b4-9145d07e4eb9.png). 

You can also try giving it to yourself in a creative world using `/give @s create:sand_filter`. The default recipe is this

![image](https://user-images.githubusercontent.com/71780401/234058499-7d17624b-f656-4251-b9e3-daed558c7d1e.png)

Let me know if you still have this issue
