### ISSUE TITLE
[Bug] [1.18.2] Config "Purification Levels" not working

### ISSUE THREAD

**Issue by Irumyuui** [ghen-git/Thirst-Mod#2]
**To Reproduce**
- Change "campfirePurificationLevels" to 3
- Launch 1.18.2, only with Thirst installed and no other mod
- Purify "Dirty" bottle of water to get "Slightly Dirty" bottle of water

**Expected Behavior**
Expected to get "Purified" instead

**Comment by ghen-git** [comment]
Oversight on my part, i had to write the config code 2 times cause i forgot to push it to git the first one and i lost it.
The 2nd time i forgot to implement the purification harshness feature. A new patch should be up by the next hour
