### ISSUE TITLE
Thirst drains incredibly quickly when under the "Nourishment" effect from Farmer's Delight food

### ISSUE THREAD

**Issue by XAURAVUS** [ghen-git/Thirst-Mod#21]
I'm not sure what I can provide in terms of logs or information, but I can confirm from my own personal testing that this happens - even when standing still, unfortunately. My version is Thirst-1.19.2-1.0.4.

**Comment by ghen-git** [comment]
Damn, thanks for letting me know, i'll fix this by this weekend, in the meantime you can downgrade to ver. 1.0.2 which doesnt have this bug
