### ISSUE TITLE
Need update for Create 0.5.1a

### ISSUE THREAD

**Issue by mlus-asuka** [ghen-git/Thirst-Mod#25]
the new version is no longer supported
-- MOD thirst --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
Caused by 1: java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/wrench/IWrenchable

**Comment by HockeyZman2000** [comment]
If you need a full log I have it here:
[latest.log](https://github.com/ghen-git/Thirst-Mod/files/11561159/latest.log)

**Comment by ranenvious** [comment]
Having this issue as well, took me hours to figure out since it kept being blamed on FTB Backups, modern ui, and midnight lib's witch hats.

**Comment by mlus-asuka** [comment]
I‘ve fork the repository and done this work on my own.And I have pulled request..
