### ISSUE TITLE
Failed to edit the item_settings file (Solved) & purity translation suggestion

### ISSUE THREAD

**Issue by CCCClear** [ghen-git/Thirst-Mod#4]
I tried to add items from other mods as water food, but I failed both in the game and in the file. 
Even when I clicked on the existing fields, they showed red, does that mean there is no way to modify this part?

**Comment by ghen-git** [comment]
Uhm, does it show an error in the editor or in the game? Also i've left a comment in the config showing the format you should use. If you tell me which items you were trying to implement i can write the config for you, so you learn the format. I'll try adding items myself to see if theres an issue in the code anyways. Thanks for the report

**Comment by CCCClear** [comment]
I tried to include Caupona's soup in the in-game config, but it didn't save whether I typed it correctly or not, even if I typed the ID of the vanilla item. 
I thought this might be simply a problem with the config itself. I tried to change it in the file again and succeeded this time. 
I'm going to close this problem because I can at least add.

**Comment by CCCClear** [comment]
By the way, can the tooltips be localized, just in case anyone has difficulty with English?

**Comment by ghen-git** [comment]
Very good idea, i'll mark this as a feature suggestion, and will implement support for the next patch. Thanks a lot for reporting
