### ISSUE TITLE
Potion Effect Visual Issues

### ISSUE THREAD

**Issue by paikeday123** [ghen-git/Thirst-Mod#42]
When the player drinks dirty water, the hunger, nausea, and poison are displayed lower than potion effects normally are. Additionally, sometimes the poison effect visually lasts forever, but doesn't do any damage. It just displays that the player has zero seconds of poison forever. I tried to clear my effects to get rid of it, but Minecraft said that I did not have any effects. The only way to get rid of the ghost poison that I have found is to give myself poison again. I am not sure what causes this glitch, because I have not seen any patterns of a certain action in the game causing this to happen. These two bugs aren't anything game breaking, but it would be nice if they could be fixed.
![2023-08-07_11 24 31](https://github.com/ghen-git/Thirst-Mod/assets/132776263/e4073fb7-f77d-47e5-8a6c-7e1a8caa4d8c)
![2023-08-07_11 24 43](https://github.com/ghen-git/Thirst-Mod/assets/132776263/eb2ef694-2996-4743-bb86-2b690edb1519)
![2023-08-07_11 30 39](https://github.com/ghen-git/Thirst-Mod/assets/132776263/8c1f98c7-6074-4206-8453-044953e6da89)
![2023-08-07_11 32 58](https://github.com/ghen-git/Thirst-Mod/assets/132776263/03cc4813-59c2-4df0-b650-0498e9d2e9c6)

**Comment by ghen-git** [comment]
yea i tried to fix it in 1.3.1, but something's wrong with how minecraft handles potion effects by itself, i cant do much more than just making the server deal with it so the client doesn't have any unsynced data, the positioning is handled by minecraft
