### ISSUE TITLE
[Suggestion] Ability to Drink form water source

### ISSUE THREAD

**Issue by ffuentesm** [ghen-git/Thirst-Mod#60]
Could you add an ability when you right-click with an empty hand on a water source block, and your thirst is not full, you take a sip of dirty water. That can help alleviate the thirst when you start the game and have no terracotta bowls or glass bottles. 

Or you could add the ability to use wooden bowls to drink water instead. Like how Coupona adds.
![image](https://github.com/ghen-git/Thirst-Mod/assets/44974827/479bd0a9-3e15-499c-a1e4-c268fa61449a)

It's just frustrating that at the start of a new game, you can die from thirst even when you have a river next to you if you are lacking those two items.

**Comment by ghen-git** [comment]
https://github.com/ghen-git/Thirst-Mod/wiki/Hydration-System#replenishing-hydration

Its already a feature, have you read the wiki?

**Comment by ffuentesm** [comment]
Well, I posted here because it's not working in 1.20.1
I am trying to drink water, but nothing happens.

**Comment by ghen-git** [comment]
Oh, sorry if its a bit obvious but i gotta ask, have you set the option in the config to true?

**Comment by ffuentesm** [comment]
I thought that was already on. 
I played this mod before, and I hadn't had to change any settings to have that mechanic before.

**Comment by mlus-asuka** [comment]
omg. i figured it out.

**Comment by Camawama** [comment]
Just had the same issue and turns out a recent update must have reset the config
