### ISSUE TITLE
Dandelion Tea can't be consumed and Fluid Tanks can't be filled with buckets

### ISSUE THREAD

**Issue by Catomax262** [ghen-git/Thirst-Mod#61]
For some reason, i can't drink dandelion tea and create fluid tanks can't be filled.

**Comment by mlus-asuka** [comment]
create fluid tank only accept water with same nbt tags

**Comment by Catomax262** [comment]
So that is a solution or not!?

**Comment by mlus-asuka** [comment]
> So that is a solution or not!?

can't replicate it. need more information

**Comment by Catomax262** [comment]
Idk, has to do with TWT i think

Mainly because of create addons?

**Comment by mlus-asuka** [comment]
> create fluid tank only accept water with same nbt tags

I mean maybe you are trying to fill a tank which already has dirty water with purity bucket.  AND what's your version?

**Comment by Catomax262** [comment]
> > create fluid tank only accept water with same nbt tags
> 
> I mean maybe you are trying to fill a tank which already has dirty water with purity bucket. AND what's your version?

No, i'm filling an empty tank with normal dirty bucket water. Version 1.3.3

**Comment by mlus-asuka** [comment]
> > > create fluid tank only accept water with same nbt tags
> > 
> > 
> > I mean maybe you are trying to fill a tank which already has dirty water with purity bucket. AND what's your version?
> 
> No, i'm filling an empty tank with normal dirty bucket water. Version 1.3.3

ok,if i could have the minimum mod list to replicate it would be better

**Comment by Catomax262** [comment]
https://gist.github.com/Catomax262/9cced9e3e3a2cc75b74d2e7092c0fd5b

**Comment by mlus-asuka** [comment]
hard to help if there are 465 mods :(

**Comment by Catomax262** [comment]
Say, it's gonna be very hard :c
