### ISSUE TITLE
Newest Version For 1.20.1 Not Working Properly With Appleskin

### ISSUE THREAD

**Issue by peepeepoopoocaca** [ghen-git/Thirst-Mod#68]
I'm not sure if it's a mod conflict or something, but the newest version that's available for 1.20.1 is not showing the water saturation bar while using Appleskin.

**Comment by mlus-asuka** [comment]
I guess you disabled it in Appleskin config

**Comment by peepeepoopoocaca** [comment]
That wouldn't make sense. My config hasn't changed since updating and reverting to the previous version of Thirst Was Taken resolves the issue. Also, all of the options in my Appleskin config are set to true.

**Comment by mlus-asuka** [comment]
> That wouldn't make sense. My config hasn't changed since updating and reverting to the previous version of Thirst Was Taken resolves the issue. Also, all of the options in my Appleskin config are set to true.

What I did in new version is just sync Appleskin config with Thirst saturation display

**Comment by mlus-asuka** [comment]
![image](https://github.com/ghen-git/Thirst-Mod/assets/80941936/11c81175-9d4d-488d-98c8-3acfb0a74bc2)

**Comment by peepeepoopoocaca** [comment]
I'm going to try deleting the config and reinstalling Appleskin to see if that fixes it.

**Comment by peepeepoopoocaca** [comment]
Still seeing this issue after deleting the old config file and reinstalling Appleskin. It could very well be a mod conflict issue, but the only mod that I could maybe see conflicting is Cold Sweat. Food saturation bar shows up fine, but thirst saturation doesn't. Very confused on this one.

**Comment by mlus-asuka** [comment]
wait, cold sweat on 1.20.1?

**Comment by peepeepoopoocaca** [comment]
Yes, Cold Sweat on 1.20.1. Also, the version of Thirst Was Taken that just came out seems to have resolved this issue. The version released on October 10th was the bugged one and it seems this issue is fixed now.

**Comment by mlus-asuka** [comment]
> Yes, Cold Sweat on 1.20.1. Also, the version of Thirst Was Taken that just came out seems to have resolved this issue. The version released on October 10th was the bugged one and it seems this issue is fixed now.

ohh! i see. yes i did fixed it in the new version
