### ISSUE TITLE
[1.20.1] This mod is not available on the server

### ISSUE THREAD

**Issue by nnn950711** [ghen-git/Thirst-Mod#69]
neoforge:
[crash-2023-10-11_18.25.59-fml.txt](https://github.com/ghen-git/Thirst-Mod/files/12868247/crash-2023-10-11_18.25.59-fml.txt)

mohist:
[crash-2023-10-11_18.07.11-fml.txt](https://github.com/ghen-git/Thirst-Mod/files/12868258/crash-2023-10-11_18.07.11-fml.txt)

**Comment by mlus-asuka** [comment]
Uploaded 1.3.4
