### ISSUE TITLE
Forge Mod Loader Crash with Thirst Mod Installed in my Custom Modpack

### ISSUE THREAD

**Issue by smellyjoe** [ghen-git/Thirst-Mod#7]
When loading up my custom modpack with thirst installed, the minecraft instance crashes with a "java.lang.reflect.InvocationTargetException" cause. Here is the crash log.
[crash-2022-12-25_14.46.08-fml.txt](https://github.com/ghen-git/Thirst-Mod/files/10300567/crash-2022-12-25_14.46.08-fml.txt)
I assume that there is a mod incompatibility, although I do not know what mods are conflicting with Thirst. Although, I know that most of the performance mods, such as Rubidium and Starlight, do not interfere with Thirst.

**Comment by smellyjoe** [comment]
Turns out, disabling Create does not cause the crash with the Thirst Mod, and enabling Create seems to cause the crash again. Downgrading the Thirst Mod to 1.1.2 seems to solve the issue.

**Comment by ghen-git** [comment]
Yea, there was a compat issue with newer versions of create, fixed with the newest patch
