### ISSUE TITLE
[Suggestion] Support for MC version 1.20

### ISSUE THREAD

**Issue by DaddelZeit** [ghen-git/Thirst-Mod#75]
Forgive me if there's a more specific reason to it, but 1.20 looks to only be unsupported because the meta files say so. The newest 1.20.1 release (1.3.4) works fine after adding 1.20 to the list of supported versions and changing the loader version from 47 to 46. I didn't test the support for other mods, though.
Would it be possible to make a dedicated 1.20 release? The mod itself is wonderful; simple and effective. Just what I needed :)

**Comment by mlus-asuka** [comment]
I can change supported version in meta files in further version
