### ISSUE TITLE
[1.19.2]Thirst drains to zero when full with satiated/stuffed effect in  "Lets do bakery" mod

### ISSUE THREAD

**Issue by DariuszNiewdana** [ghen-git/Thirst-Mod#82]
I am playing on modpack with mods from "Lets do" collection and mod "Let's do bakery" have a problem where some items give satiated/stuffed effect and it drains thirst to zero, but only when its full. If i have less than full thirst bar, then the bug does not apear.

I saw that similiar problem was with farmer's delight awhile back so maybe similiar issue. Also someone has made a post in "issues" channel on "Let's do" developer discord and they said that its propably not fixable on their part

**Comment by ghen-git** [comment]
fixed in the latest patch 🔥
