### ISSUE TITLE
Putting water in a cauldron completely removes impurities from water.

### ISSUE THREAD

**Issue by MidasMonkey** [ghen-git/Thirst-Mod#9]
If you put a bottle or bucket of dirty water into a cauldron and then pull it out the water instantly becomes purified, making all other methods of purifying water useless.

**Comment by ghen-git** [comment]
Yup, i had already tackled the issue as you can see in [this](https://github.com/ghen-git/Thirst-Mod/blob/258d5e930c558f30448b6dd631640e834058d7d7/src/main/java/dev/ghen/thirst/foundation/mixin/MixinBootstrap.java#L37) line of code, but it probably broke with newer patches, i'll try and get it to work again

**Comment by ghen-git** [comment]
alr, the newest patch fixes it
