### ISSUE TITLE
making teas from purified water gives dirty or slightly dirty tea

### ISSUE THREAD

**Issue by Kynz0** [ghen-git/Thirst-Mod#93]
when iam trying to make any tea from the farmers [respite mod](https://www.curseforge.com/minecraft/mc-mods/farmers-respite-fabric) and the [central kitchen mod](https://modrinth.com/mod/create-central-kitchen) and iam using purified water in the basin the outcome is either dirty tea or slightly dirty tea.

**Comment by mlus-asuka** [comment]
Already fixed, but ghen needs to prepare something before 1.3.6 release

**Comment by Kynz0** [comment]
nice thanks (i actually managed to make the tea farm using a deployer with purified water bottles on the kettle and then using funnels on the kettle to put the ingredients in and the tea out :D)
